### ISSUE TITLE
Slow jitting benchmarks

### ISSUE THREAD

**Issue by pnkraemer** [pnkraemer/million-dimension-prob-ode-solver-experiments#15]
#14 introduces a benchmark-option that just-in-time-compiles the attempt_step functions.
This is for two reasons:
1) It is interesting to see how much (wall-clock) run time one can gain by using a few additional tricks
2) The run-time curves will look less noisy ("cleaner").

Since this makes the experiment really slow (compilation takes a while), it is turned off by default and should only be turned on when desired.

If we notice that we never turn it on, let's remove it again!

**Comment by pnkraemer** [comment]
At the moment the jitted experiments look better than the non-jitted:

[1_attempt_step_lorenz_timing.pdf](https://github.com/pnkraemer/high-dimensional-ode-solver-experiments/files/7009009/1_attempt_step_lorenz_timing.pdf)

(better in the sense that growth rates are more evident). Maybe that is an argument in favour of keeping them...!? Let's just keep an eye on them

**Comment by nathanaelbosch** [comment]
Without having experienced the slow compile times, I'm strongly in favor of just jitting everything we can! It seems like a super simple way to make things faster and so I don't see a good reason for reporting the slower runtimes, if we also have faster ones. 

And the curves really do look much nicer :)
