### ISSUE TITLE
Experiment 2 ToDo's

### ISSUE THREAD

**Issue by schmidtjonathan** [pnkraemer/million-dimension-prob-ode-solver-experiments#22]
There are a few reasons why we think the plots yielded by experiment 2 look not entirely, as we expect:

1. Use a **fully JITted version** of the run, in order to remove remaining noise in the run-time
2. Track the **number of evaluations** of each solve
3. The **EK1 is at the moment faster than the EK0**, because it is better optimized
4. The diagonal EK1 builds the **full Jacobian**, which can (and will) be avoided
5. We could neglect the cost of the **initialization**, which would probably reduce the overall runtime of each run
6. We would probably see more interesting results for much higher dimensions than 10 (maybe use three different scales for the dimensions for the plots, e.g. 10, 50, 100)

**Comment by pnkraemer** [comment]
See also #61 in tornado
