### ISSUE TITLE
Is this the final repo name?

### ISSUE THREAD

**Issue by nathanaelbosch** [pnkraemer/million-dimension-prob-ode-solver-experiments#60]
Just wanted to raise the question since it can still be changed, but in general I think I'm fine with this repo name. 

The only alternative that comes to my mind is "ode-filter" instead of "ode-solver"?

But we can also keep it as it is, again I just wanted to make sure that we consciously decide on a public repo name.

**Comment by pnkraemer** [comment]
guess this is resolved now :)
